### PR TITLE
Removed weird gap that was part of dropdown

### PR DESCRIPTION
**Pull request by peterbrinck**

### CODE REVIEW

**Comment by aheinze** [comment]
thanks for the contribution, but this gap is intentional ;-)

**Comment by peterbrinck** [comment]
But the gap is annoying, because the gap acts as part of the dropdown :-(

**Comment by aheinze** [comment]
hope this commit helps https://github.com/COCOPi/cocopi-kickstart/commit/6e295c306c853561f152aba7fcc216076c089ec3

**Comment by peterbrinck** [comment]
Oh yes! :smiley:

**Pull request closed without merging**
